version: '3.8'

services:
  whatsapp-bot:
    build: .
    container_name: whatsapp-ai-bot
    restart: unless-stopped
    ports:
      - "3002:3002"
    volumes:
      # Persistir datos de autenticación de WhatsApp
      - ./auth_info:/app/auth_info
      # Persistir conversaciones
      - ./conversations:/app/conversations
      # Archivos públicos (interfaz web)
      - ./public:/app/public
    environment:
      - NODE_ENV=production
      - PORT=3002
      - TZ=America/Bogota
      # Configuración de AI (opcional - descomenta si usas OpenAI o Gemini)
      # - OPENAI_API_KEY=${OPENAI_API_KEY}
      # - GEMINI_API_KEY=${GEMINI_API_KEY}
      # - AI_PROVIDER=ollama
    networks:
      - whatsapp-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3002/api/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx (opcional - para proxy reverso y SSL)
  nginx:
    image: nginx:alpine
    container_name: whatsapp-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - whatsapp-bot
    networks:
      - whatsapp-network

networks:
  whatsapp-network:
    driver: bridge